name: Test GHA

on:
  pull_request:
    types: [closed]

jobs:
  echo-pr-event:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event
        id: echo-event
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "Checking PR_NUMBER: $PR_NUMBER"
      - name: Print git branch and hash
        run: |
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit Hash: $(git rev-parse HEAD)"
