name: Test GHA

on:
  push: {}

jobs:
  echo-pr-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print git branch, hash and PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit Hash: $(git rev-parse HEAD)"
          echo "Pull request number: $PR_NUMBER"
          echo "About to wait at $(date +'%H:%M:%S %Z %d/%m/%y')"
      - name: Wait for 30 seconds
        run: sleep 30
